### ISSUE TITLE
Icon is not displayed in live preview & source modes

### ISSUE THREAD

**Issue by KkEi34** [joethei/obsidian-link-favicon#62] opened 2023-04-25 18:37 UTC
Windows 10.0.19045 x64
Obsidian 1.1.16 (Installer v.0.15.9)
Link Favicons 1.8.1

Steps to reproduce:
1. Create empty vault
2. Install & activate plugin
3. restart obsidian
4. create note
5. add link `[issues](https://github.com/joethei/obsidian-link-favicon/issues)`
Result:
Icon is displayed only in reading mode (see image below)
Expected:
Icon is displayed in reading, live preview and source mode.

![noIcon](https://user-images.githubusercontent.com/111685012/234369257-927fefd3-a828-4beb-8be2-6ac159cd57f4.gif)

**Comment by liuke101** [comment] 2023-04-30 16:37
I had the same problem

**Comment by meinCF** [comment] 2023-05-03 04:30
I had the same problem.

**Comment by tdcqin** [comment] 2023-05-07 15:38
I had the same problem

**Comment by iljapanic** [comment] 2023-07-09 19:10
Same here. Still haven't found a way to fix it.

**Comment by NomarCub** [comment] 2023-07-14 19:11
@joethei do you plan on spending time on this plugin any time soon? Would you accept pull requests, or others forking or taking over?
I rely on this functionality for day to day use, and it's really annoying to have this spotty functionality.

**Comment by joethei** [comment] 2023-07-14 19:19
Feel free to send a PR, I haven't been able to find a fix for this yet

**Comment by hy4l** [comment] 2023-07-19 23:11
I have the same issue. I use Win11pro Version 22H2 (0S Build 22621.1992). I also reported issues with ProZen plugin in case if it's related or somebody will find a connection between issues and OS.

My plugins are:
[
  "obsidian-image-toolkit",
  "folder-note-plugin",
  "obsidian-prozen",
  "obsidian-upcoming",
  "obsidian-tagfolder",
  "tag-wrangler",
  "settings-search",
  "obsidian-admonition",
  "obsidian-banners",
  "cmdr",
  "cycle-through-panes",
  "dataview",
  "cm-editor-syntax-highlight-obsidian",
  "emoji-shortcodes",
  "excalibrain",
  "obsidian-excalidraw-plugin",
  "obsidian-file-color",
  "obsidian-file-path-to-uri",
  "highlightr-plugin",
  "homepage",
  "obsidian-icon-folder",
  "obsidian-note-autocreator",
  "obsidian-plugin-update-tracker",
  "recent-files-obsidian"
] 
Cheers,
hyal

**Closed** 2023-09-12 19:56 UTC

**Comment by hy4l** [comment] 2023-09-12 21:14
I tested 1.8.2, different vaults and sandboxes and it doesn't fix on W11 Obsidian 1.14.12. The same issue:

<img width="106" alt="image" src="https://github.com/joethei/obsidian-link-favicon/assets/140013867/b1fc2cb9-42ff-40fd-a272-47477b88e7c1">
<img width="113" alt="image" src="https://github.com/joethei/obsidian-link-favicon/assets/140013867/bba1e786-d1f1-40ca-a010-4faf9d384112">

**Comment by nhan000** [comment] 2023-09-13 02:17
1.8.1 worked fine but after updating to 1.8.2, the plugin stopped working for me in all 3 modes.
Obsidian 1.4.11, Windows 11.

**Comment by NomarCub** [comment] 2023-09-13 05:11
Live preview completely broke for me too.

**Comment by mii-key** [comment] 2023-09-13 07:52
Unfortunately doesn't work.
Windows 11 x64
Obsidian 1.4.12
Link Favicons 1.8.2

![no-icon](https://github.com/joethei/obsidian-link-favicon/assets/130221089/e88e8fba-9bc0-428d-948f-e277fbcfc9bd)

**Comment by joethei** [comment] 2023-09-14 19:05
I can't reproduce this, now I am confused.
Can any of you run `app.plugins.plugins['link-favicon'].isUsingLivePreviewEnabledEditor()` in the dev console and post here what it returns?

**Comment by KillyMXI** [comment] 2023-09-14 19:58
![image](https://github.com/joethei/obsidian-link-favicon/assets/13851064/3b1cad63-6795-45ba-acd9-0da363e4c11a)

A line with a link in Live Preview:

![image](https://github.com/joethei/obsidian-link-favicon/assets/13851064/12dbed8d-49b1-4824-a148-c98be687af1d)

When opening a page, I get this uncaught error in console:

<details>
  <summary>Click to show</summary>

```
plugin:link-favicon:7 Uncaught (in promise) undefined
p @ plugin:link-favicon:7
Promise.then (async)
m @ plugin:link-favicon:7
eval @ plugin:link-favicon:7
I @ plugin:link-favicon:7
updateAsyncDecorations @ plugin:link-favicon:7
l @ app.js:1
c @ app.js:1
setTimeout (async)
c @ app.js:1
setTimeout (async)
u @ app.js:1
buildAsyncDecorations @ plugin:link-favicon:7
eval @ plugin:link-favicon:7
(anonymous) @ app.js:1
e.update @ app.js:1
e.setState @ app.js:1
t.set @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:obsidian-excalidraw-plugin:79
r @ plugin:obsidian-excalidraw-plugin:79
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onFileClick @ app.js:1
s @ enhance.js:1
```

</details>

**Comment by joethei** [comment] 2023-09-14 20:36
Also can you try and see if 1.8.3 fixes this?

**Comment by KillyMXI** [comment] 2023-09-14 20:49
1.8.3 shows the favicons.
No uncaught error in console.

The `console.log` you've left in the code dumps a lot of garbage to console.
Besides the links like this:
![image](https://github.com/joethei/obsidian-link-favicon/assets/13851064/e45c3e16-db2f-4291-9d63-7fd3b0a480db)

it also dumps code blocks there for some reason...

![image](https://github.com/joethei/obsidian-link-favicon/assets/13851064/c42a9b1c-f2da-4e84-80f4-63dbc4fa2a42)

They are not broken, fortunately. But I don't think this extension should touch them in any way.

**Comment by hy4l** [comment] 2023-09-14 20:52
> Also can you try and see if 1.8.3 fixes this?

<img width="128" alt="image" src="https://github.com/joethei/obsidian-link-favicon/assets/140013867/266ea7df-547e-47d9-86e6-298e00237f21">
<img width="123" alt="image" src="https://github.com/joethei/obsidian-link-favicon/assets/140013867/2a90497e-30ad-4c62-a7f6-46de199a476c">

![son-jeff-goldblum-crazy-son-of-a-bitch](https://github.com/joethei/obsidian-link-favicon/assets/140013867/b7cbdc71-e7ad-4b03-8a4d-f78d8fec6e65)
![feelsGood](https://github.com/joethei/obsidian-link-favicon/assets/140013867/7ffc11a0-c37b-46f9-a881-acea6c417a64)
![leo_celeb](https://github.com/joethei/obsidian-link-favicon/assets/140013867/de302e46-933c-44a4-9148-ad097318891e)

**Comment by nhan000** [comment] 2023-09-14 23:17
1.8.3 works for me.

**Comment by mii-key** [comment] 2023-09-15 17:28
1.8.3 works.
Great job! Thanks!
